[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/books/*"
  to = "/books/:splat"
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
