[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
